.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH RGNOME 1 "September 23, 2007"
.SH NAME
rgnome \- a frontend for GNU R
.SH SYNOPSIS
.B rgnome
.RI [\fIoptions\fR]... [\fIfilename\fR]...
.SH DESCRIPTION
.B rgnome
RGnome is a gtk based frontend for GNU R, which is a widely 
used language for statistical computing. It features a fully 
working R console and an editor with syntax highlighting.
 
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options and exit
.TP
.B \-v, \-\-version
Show version information
.TP

.SH SEE ALSO
More information is available on the
.B rgnome 
web page:
.IR http://rgnome.sf.net

.SH AUTHOR
.B rgnome
was written by Gordon Bergling <gordon@boltzmann-konstante.de> and
Luca Della Santina <dsantina@farm.unipi.it>
.P
This manual page was written by Gordon Bergling <gordon@boltzmann-konstante.de> 
